/**
*****************************************************************************************
*     Copyright(c) 2023, Realtek Semiconductor Corporation. All rights reserved.
*****************************************************************************************
* @file    flash_map.h
* @brief   Flash Layout Configuration, and flash layout must be changed with config file!
* @note    flash_map.h must be generated by FlashMapGenerateTool!
* *************************************************************************************
*/

#ifndef _FLASH_MAP_H_
#define _FLASH_MAP_H_

#ifdef __cplusplus
extern "C" {
#endif

/*============================================================================*
*                        Flash Layout
*============================================================================*/
/*  Flash total size                                1024KB
example:
    1) Reserved:                                       4K (0x00800000)
    2) OEM Header:                                     4K (0x00801000)
    3) OTA Bank0:                                    500K (0x00802000)
        a) OTA Header                    4K (0x00802000)
        b) Secure boot loader            4K (0x0080A000)
        c) Patch code                   28K (0x00803000)
        d) BT Stack Patch Code          40K (0x0080B000)
        e) Upperstack  Code              0K (0x00815000)
        f) APP code                    424K (0x00815000)
        g) APP data1                     0K (0x00858000)
        h) APP data2                     0K (0x00858000)
        i) APP data3                     0K (0x00858000)
        j) APP data4                     0K (0x00858000)
        k) APP data5                     0K (0x00858000)
        l) APP Config File               0K (0x00858000)
    4) OTA Bank1:                                    500K (0x0087F000)
        a) OTA Header                    4K (0x0087F000)
        b) Secure boot loader            4K (0x00880000)
        c) Patch code                   28K (0x00881000)
        d) BT Stack Patch Code          28K (0x00888000)
        e) Upperstack Code               0K (0x0088F000)
        f) APP code                    424K (0x0088F000)
        g) APP data1                     0K (0x008AE000)
        h) APP data2                     0K (0x008AE000)
        i) APP data3                     0K (0x008AE000)
        j) APP data4                     0K (0x008AE000)
        k) APP data5                     0K (0x008AE000)
        l) APP Config File               0K (0x00000000)
    5) FTL:                                           16K (0x008FC000)
    6) OTA Tmp:                                        0K (0x008B2000)
    7) user data1:                            0K (0x008B2000)
    8) user data2:                            0K (0x008B2000)
*/

/*============================================================================*
*            Flash Layout Configuration (Generated by FlashMapGenerateTool)
*============================================================================*/

#define FLASH_ADDR                      0x00800000  //Fixed
#define FLASH_MAX_SIZE                  0x00100000  //1024K Bytes

/* ========== High Level Flash Layout Configuration ========== */
#define RESERVED_ADDR                   0x00800000
#define RESERVED_SIZE                   0x00001000  //4K Bytes
#define OEM_CFG_ADDR                    0x00801000
#define OEM_CFG_SIZE                    0x00001000  //4K Bytes
#define OTA_BANK0_ADDR                  0x00802000
#define OTA_BANK0_SIZE                  0x0007D000  //500K Bytes
#define OTA_BANK1_ADDR                  0x0087F000
#define OTA_BANK1_SIZE                  0x0007D000  //500K Bytes
#define FTL_ADDR                        0x008FC000
#define FTL_SIZE                        0x00004000  //16K Bytes
#define OTA_TMP_ADDR                    0x008B2000
#define OTA_TMP_SIZE                    0x00000000  //0K Bytes
#define USER_DATA1_ADDR                 0x008B2000
#define USER_DATA1_SIZE                 0x00000000  //0K Bytes
#define USER_DATA2_ADDR                 0x008B2000
#define USER_DATA2_SIZE                 0x00000000  //0K Bytes

/* ========== OTA Bank0 Flash Layout Configuration ========== */
#define BANK0_OTA_HEADER_ADDR           0x00802000
#define BANK0_OTA_HEADER_SIZE           0x00001000  //4K Bytes
#define BANK0_SECURE_BOOT_ADDR          0x0080A000
#define BANK0_SECURE_BOOT_SIZE          0x00001000  //4K Bytes
#define BANK0_ROM_PATCH_ADDR            0x00803000
#define BANK0_ROM_PATCH_SIZE            0x00007000  //28K Bytes
#define BANK0_BT_STACK_PATCH_ADDR       0x0080B000
#define BANK0_BT_STACK_PATCH_SIZE       0x0000A000  //40K Bytes
#define BANK0_UPPERSTACK_ADDR           0x00815000
#define BANK0_UPPERSTACK_SIZE           0x00000000  //0K Bytes
#define BANK0_APP_ADDR                  0x00815000
#define BANK0_APP_SIZE                  0x0006A000  //424K Bytes
#define BANK0_APP_DATA1_ADDR            0x00858000
#define BANK0_APP_DATA1_SIZE            0x00000000  //0K Bytes
#define BANK0_APP_DATA2_ADDR            0x00858000
#define BANK0_APP_DATA2_SIZE            0x00000000  //0K Bytes
#define BANK0_APP_DATA3_ADDR            0x00858000
#define BANK0_APP_DATA3_SIZE            0x00000000  //0K Bytes
#define BANK0_APP_DATA4_ADDR            0x00858000
#define BANK0_APP_DATA4_SIZE            0x00000000  //0K Bytes
#define BANK0_APP_DATA5_ADDR            0x00858000
#define BANK0_APP_DATA5_SIZE            0x00000000  //0K Bytes
#define BANK0_APP_CONFIG_FILE_ADDR      0x00858000
#define BANK0_APP_CONFIG_FILE_SIZE      0x00000000  //0K Bytes

/* ========== OTA Bank1 Flash Layout Configuration ========== */
#define BANK1_OTA_HEADER_ADDR           0x0087F000
#define BANK1_OTA_HEADER_SIZE           0x00001000  //4K Bytes
#define BANK1_SECURE_BOOT_ADDR          0x00880000
#define BANK1_SECURE_BOOT_SIZE          0x00001000  //4K Bytes
#define BANK1_ROM_PATCH_ADDR            0x00881000
#define BANK1_ROM_PATCH_SIZE            0x00007000  //28K Bytes
#define BANK1_BT_STACK_PATCH_ADDR       0x00888000
#define BANK1_BT_STACK_PATCH_SIZE       0x00007000  //28K Bytes
#define BANK1_UPPERSTACK_ADDR           0x0088F000
#define BANK1_UPPERSTACK_SIZE           0x00000000  //0K Bytes
#define BANK1_APP_ADDR                  0x0088F000
#define BANK1_APP_SIZE                  0x0006A000  //424K Bytes
#define BANK1_APP_DATA1_ADDR            0x008AE000
#define BANK1_APP_DATA1_SIZE            0x00000000  //0K Bytes
#define BANK1_APP_DATA2_ADDR            0x008AE000
#define BANK1_APP_DATA2_SIZE            0x00000000  //0K Bytes
#define BANK1_APP_DATA3_ADDR            0x008AE000
#define BANK1_APP_DATA3_SIZE            0x00000000  //0K Bytes
#define BANK1_APP_DATA4_ADDR            0x008AE000
#define BANK1_APP_DATA4_SIZE            0x00000000  //0K Bytes
#define BANK1_APP_DATA5_ADDR            0x008AE000
#define BANK1_APP_DATA5_SIZE            0x00000000  //0K Bytes
#define BANK1_APP_CONFIG_FILE_ADDR      0x00000000
#define BANK1_APP_CONFIG_FILE_SIZE      0x00000000  //0K Bytes


#ifdef __cplusplus
}
#endif
/** @} */ /* _FLASH_MAP_H_ */
#endif
