/**
*****************************************************************************************
*     Copyright(c) 2022, Realtek Semiconductor Corporation. All rights reserved.
*****************************************************************************************
* @file    flash_map.h
* @brief   Flash Layout Configuration, and flash layout must be changed with config file!
* @note    flash_map.h must be generated by FlashMapGenerateTool!
* *************************************************************************************
*/

#ifndef _FLASH_MAP_H_
#define _FLASH_MAP_H_

#ifdef __cplusplus
extern "C" {
#endif

/*============================================================================*
*                        Flash Layout
*============================================================================*/
/*  Flash total size                                1024KB
example:
    1) Reserved:                                          4K (0x04000000)
    2) OEM Header:                                        4K (0x04001000)
    3) Bank0 Boot Patch Code:                            32K (0x04002000)
    4) Bank1 Boot Patch Code:                            32K (0x0400A000)
    5) OTA Bank0:                                       520K (0x04012000)
        a) OTA Header                    4K (0x04012000)
        b) System Patch code            32K (0x04013000)
        c) BT Stack Patch code          72K (0x0401B000)
        d) BT Host code                  0K (0x0402D000)
        e) APP code                    412K (0x0402D000)
        f) APP Config File               0K (0x04094000)
        g) APP data1                     0K (0x04094000)
        h) APP data2                     0K (0x04094000)
        i) APP data3                     0K (0x04094000)
        j) APP data4                     0K (0x04094000)
        k) APP data5                     0K (0x04094000)
        l) APP data6                     0K (0x04094000)
    6) OTA Bank1:                                         0K (0x04094000)
        a) OTA Header                    0K (0x00000000)
        b) System Patch code             0K (0x00000000)
        c) BT Stack Patch code           0K (0x00000000)
        d) BT Host code                  0K (0x00000000)
        e) APP code                      0K (0x00000000)
        f) APP Config File               0K (0x00000000)
        g) APP data1                     0K (0x00000000)
        h) APP data2                     0K (0x00000000)
        i) APP data3                     0K (0x00000000)
        j) APP data4                     0K (0x00000000)
        k) APP data5                     0K (0x00000000)
        l) APP data6                     0K (0x00000000)
    7) Bank0 Secure APP Code:                             0K (0x04094000)
    8) Bank0 Secure APP Data:                             0K (0x04094000)
    9) Bank1 Secure APP Code:                             0K (0x04094000)
    10) Bank1 Secure APP Data:                            0K (0x04094000)
    11) RO DATA1:                                         0K (0x04094000)
    12) RO DATA2:                                         0K (0x04094000)
    13) RO DATA3:                                         0K (0x04094000)
    14) RO DATA4:                                         0K (0x04094000)
    15) RO DATA5:                                         0K (0x04094000)
    16) RO DATA6:                                         0K (0x04094000)
    17) OTA Tmp:                                        416K (0x04094000)
    18) FTL:                                             16K (0x040FC000)
    19) user data1:                                       0K (0x04100000)
    20) user data2:                                       0K (0x04100000)
    21) user data3:                                       0K (0x04100000)
    22) user data4:                                       0K (0x04100000)
    23) user data5:                                       0K (0x04100000)
    24) user data6:                                       0K (0x04100000)
    25) user data7:                                       0K (0x04100000)
    26) user data8:                                       0K (0x04100000)
    27) APP Defined Section1:                             0K (0x04100000)
    28) APP Defined Section2:                             0K (0x04100000)
*/

/*============================================================================*
*            Flash Layout Configuration (Generated by FlashMapGenerateTool)
*============================================================================*/

#define FLASH_START_ADDR                0x04000000  //Fixed
#define FLASH_MAX_SIZE                  0x00100000  //1024K Bytes

/* ========== High Level Flash Layout Configuration ========== */
#define OEM_CFG_ADDR                    0x04001000
#define OEM_CFG_SIZE                    0x00001000  //4K Bytes
#define BANK0_BOOT_PATCH_ADDR           0x04002000
#define BANK0_BOOT_PATCH_SIZE           0x00008000  //32K Bytes
#define BANK1_BOOT_PATCH_ADDR           0x0400A000
#define BANK1_BOOT_PATCH_SIZE           0x00008000  //32K Bytes
#define OTA_BANK0_ADDR                  0x04012000
#define OTA_BANK0_SIZE                  0x00082000  //520K Bytes
#define OTA_BANK1_ADDR                  0x04094000
#define OTA_BANK1_SIZE                  0x00000000  //0K Bytes
#define BANK0_SECURE_APP_ADDR           0x04094000
#define BANK0_SECURE_APP_SIZE           0x00000000  //0K Bytes
#define BANK0_SECURE_APP_DATA_ADDR      0x04094000
#define BANK0_SECURE_APP_DATA_SIZE      0x00000000  //0K Bytes
#define BANK1_SECURE_APP_ADDR           0x04094000
#define BANK1_SECURE_APP_SIZE           0x00000000  //0K Bytes
#define BANK1_SECURE_APP_DATA_ADDR      0x04094000
#define BANK1_SECURE_APP_DATA_SIZE      0x00000000  //0K Bytes
#define RO_DATA1_ADDR                   0x04094000
#define RO_DATA1_SIZE                   0x00000000  //0K Bytes
#define RO_DATA2_ADDR                   0x04094000
#define RO_DATA2_SIZE                   0x00000000  //0K Bytes
#define RO_DATA3_ADDR                   0x04094000
#define RO_DATA3_SIZE                   0x00000000  //0K Bytes
#define RO_DATA4_ADDR                   0x04094000
#define RO_DATA4_SIZE                   0x00000000  //0K Bytes
#define RO_DATA5_ADDR                   0x04094000
#define RO_DATA5_SIZE                   0x00000000  //0K Bytes
#define RO_DATA6_ADDR                   0x04094000
#define RO_DATA6_SIZE                   0x00000000  //0K Bytes
#define OTA_TMP_ADDR                    0x04094000
#define OTA_TMP_SIZE                    0x00068000  //416K Bytes
#define FTL_ADDR                        0x040FC000
#define FTL_SIZE                        0x00004000  //16K Bytes
#define USER_DATA1_ADDR                 0x04100000
#define USER_DATA1_SIZE                 0x00000000  //0K Bytes
#define USER_DATA2_ADDR                 0x04100000
#define USER_DATA2_SIZE                 0x00000000  //0K Bytes
#define USER_DATA3_ADDR                 0x04100000
#define USER_DATA3_SIZE                 0x00000000  //0K Bytes
#define USER_DATA4_ADDR                 0x04100000
#define USER_DATA4_SIZE                 0x00000000  //0K Bytes
#define USER_DATA5_ADDR                 0x04100000
#define USER_DATA5_SIZE                 0x00000000  //0K Bytes
#define USER_DATA6_ADDR                 0x04100000
#define USER_DATA6_SIZE                 0x00000000  //0K Bytes
#define USER_DATA7_ADDR                 0x04100000
#define USER_DATA7_SIZE                 0x00000000  //0K Bytes
#define USER_DATA8_ADDR                 0x04100000
#define USER_DATA8_SIZE                 0x00000000  //0K Bytes
#define BKP_DATA1_ADDR                  0x04100000
#define BKP_DATA1_SIZE                  0x00000000  //0K Bytes
#define BKP_DATA2_ADDR                  0x04100000
#define BKP_DATA2_SIZE                  0x00000000  //0K Bytes

/* ========== OTA Bank0 Flash Layout Configuration ========== */
#define BANK0_OTA_HDR_ADDR              0x04012000
#define BANK0_OTA_HDR_SIZE              0x00001000  //4K Bytes
#define BANK0_SYSTEM_PATCH_ADDR         0x04013000
#define BANK0_SYSTEM_PATCH_SIZE         0x00008000  //32K Bytes
#define BANK0_BT_STACK_PATCH_ADDR       0x0401B000
#define BANK0_BT_STACK_PATCH_SIZE       0x00012000  //72K Bytes
#define BANK0_BT_HOST_ADDR              0x0402D000
#define BANK0_BT_HOST_SIZE              0x00000000  //0K Bytes
#define BANK0_APP_ADDR                  0x0402D000
#define BANK0_APP_SIZE                  0x00067000  //412K Bytes
#define BANK0_APP_CONFIG_FILE_ADDR      0x04094000
#define BANK0_APP_CONFIG_FILE_SIZE      0x00000000  //0K Bytes
#define BANK0_APP_DATA1_ADDR            0x04094000
#define BANK0_APP_DATA1_SIZE            0x00000000  //0K Bytes
#define BANK0_APP_DATA2_ADDR            0x04094000
#define BANK0_APP_DATA2_SIZE            0x00000000  //0K Bytes
#define BANK0_APP_DATA3_ADDR            0x04094000
#define BANK0_APP_DATA3_SIZE            0x00000000  //0K Bytes
#define BANK0_APP_DATA4_ADDR            0x04094000
#define BANK0_APP_DATA4_SIZE            0x00000000  //0K Bytes
#define BANK0_APP_DATA5_ADDR            0x04094000
#define BANK0_APP_DATA5_SIZE            0x00000000  //0K Bytes
#define BANK0_APP_DATA6_ADDR            0x04094000
#define BANK0_APP_DATA6_SIZE            0x00000000  //0K Bytes

/* ========== OTA Bank1 Flash Layout Configuration ========== */
#define BANK1_OTA_HDR_ADDR              0x00000000
#define BANK1_OTA_HDR_SIZE              0x00000000  //0K Bytes
#define BANK1_SYSTEM_PATCH_ADDR         0x00000000
#define BANK1_SYSTEM_PATCH_SIZE         0x00000000  //0K Bytes
#define BANK1_BT_STACK_PATCH_ADDR       0x00000000
#define BANK1_BT_STACK_PATCH_SIZE       0x00000000  //0K Bytes
#define BANK1_BT_HOST_ADDR              0x00000000
#define BANK1_BT_HOST_SIZE              0x00000000  //0K Bytes
#define BANK1_APP_ADDR                  0x00000000
#define BANK1_APP_SIZE                  0x00000000  //0K Bytes
#define BANK1_APP_CONFIG_FILE_ADDR      0x00000000
#define BANK1_APP_CONFIG_FILE_SIZE      0x00000000  //0K Bytes
#define BANK1_APP_DATA1_ADDR            0x00000000
#define BANK1_APP_DATA1_SIZE            0x00000000  //0K Bytes
#define BANK1_APP_DATA2_ADDR            0x00000000
#define BANK1_APP_DATA2_SIZE            0x00000000  //0K Bytes
#define BANK1_APP_DATA3_ADDR            0x00000000
#define BANK1_APP_DATA3_SIZE            0x00000000  //0K Bytes
#define BANK1_APP_DATA4_ADDR            0x00000000
#define BANK1_APP_DATA4_SIZE            0x00000000  //0K Bytes
#define BANK1_APP_DATA5_ADDR            0x00000000
#define BANK1_APP_DATA5_SIZE            0x00000000  //0K Bytes
#define BANK1_APP_DATA6_ADDR            0x00000000
#define BANK1_APP_DATA6_SIZE            0x00000000  //0K Bytes


#ifdef __cplusplus
}
#endif
/** @} */ /* _FLASH_MAP_H_ */
#endif
