#ifndef _LOG_TRACE_H_
#define _LOG_TRACE_H_

#ifdef __cplusplus
extern "C"
{
#endif

#define IMG_TRACE_ADR             (0xE0100000)
#define MAX_IMG_TRACE_SIZE        (0x00FFFFFF)
#define ROM_TRACE_START           IMG_TRACE_ADR
#define ROM_TRACE_SIZE            (0x000A0000)
#define BOOT_PATCH_TRACE_START    (ROM_TRACE_START + ROM_TRACE_SIZE)
#define BOOT_PATCH_TRACE_SIZE     (0x00400000)
#define UPPER_STACK_START         (BOOT_PATCH_TRACE_START + BOOT_PATCH_TRACE_SIZE)
#define UPPER_STACK_SIZE          (0x000A0000)
#define APP_TRACE_START           (UPPER_STACK_START + UPPER_STACK_SIZE)
#define APP_TRACE_SIZE            (0x00400000)
#define DSPAUDIO_TRACE_START      (APP_TRACE_START + APP_TRACE_SIZE)
#define DSPAUDIO_TRACE_SIZE       (0x00010000)
#define DSPVOICE_TRACE_START      (DSPAUDIO_TRACE_START + DSPAUDIO_TRACE_SIZE)
#define DSPVOICE_TRACE_SIZE       (0x00010000)
#define DSPPATCH_TRACE_START      (DSPVOICE_TRACE_START + DSPVOICE_TRACE_SIZE)
#define DSPPATCH_TRACE_SIZE       (0x00008000)
#define DSPAPP_TRACE_START        (DSPPATCH_TRACE_START + DSPPATCH_TRACE_SIZE)
#define DSPAPP_TRACE_SIZE         (0x00018000)
#define TOTAL_TRACE_SIZE          (ROM_TRACE_SIZE + BOOT_PATCH_TRACE_SIZE + UPPER_STACK_SIZE + \
                                   APP_TRACE_SIZE + DSPAUDIO_TRACE_SIZE + DSPVOICE_TRACE_SIZE + \
                                   DSPPATCH_TRACE_SIZE + DSPAPP_TRACE_SIZE)

#if (TOTAL_TRACE_SIZE > MAX_IMG_TRACE_SIZE)
#error "TOTAL_TRACE_SIZE SHOULD BE SMALLER THAN MAX_IMG_TRACE_SIZE"
#endif

#ifdef __cplusplus
}
#endif

#endif /* _LOG_TRACE_H_ */
